name: 'safestreets'
version: '1.0.0'

profile: 'safestreets'

model-paths: ["takeHomeAssessment-dataEngineer/models"]
analysis-paths: ["takeHomeAssessment-dataEngineer/analyses"]
test-paths: ["takeHomeAssessment-dataEngineer/tests"]
seed-paths: ["takeHomeAssessment-dataEngineer/seeds"]
macro-paths: ["takeHomeAssessment-dataEngineer/macros"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  safestreets:
    +schema: raw

models:
  safestreets:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
